package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
* Attribute generated by hbm2java
*/
public class Attribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5501729405856240275L;
	private int attrbid;
	private String description;
	private String attrbname;
	private String attrbtype;
	private String attrbphysicaltype;
	private Date dtlstupdt;
	private Long lstupdtuid;
	private char isdoc;
	private Set<ProgramAttribute> prgrmattrbs = new HashSet<ProgramAttribute>(0);
	private Set<LoanAttribute> lnattrbs = new HashSet<LoanAttribute>(0);

	public Attribute() {
	}

	public Attribute(int attrbid) {
		this.attrbid = attrbid;
	}

	public Attribute(int attrbid, String description, String attrbname,
			String attrbtype, String attrbphysicaltype, Date dtlstupdt, char isdoc,
			Long lstupdtuid, Set<ProgramAttribute> prgrmattrbs, Set<LoanAttribute> lnattrbs) {
		this.attrbid = attrbid;
		this.description = description;
		this.attrbname = attrbname;
		this.attrbtype = attrbtype;
		this.attrbphysicaltype = attrbphysicaltype;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
		this.isdoc = isdoc;
		this.prgrmattrbs = prgrmattrbs;
		this.lnattrbs = lnattrbs;
	}
	
	public char getIsDoc(){
		return isdoc;
	}
	
	public void setIsDoc(char isdoc){
		this.isdoc = isdoc;
	}
	
	/**
	 * @return the attrbid
	 */
	public int getAttrbid() {
		return attrbid;
	}

	/**
	 * @param attrbid the attrbid to set
	 */
	public void setAttrbid(int attrbid) {
		this.attrbid = attrbid;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the attrbname
	 */
	public String getAttrbname() {
		return attrbname;
	}

	/**
	 * @param attrbname the attrbname to set
	 */
	public void setAttrbname(String attrbname) {
		this.attrbname = attrbname;
	}

	/**
	 * @return the attrbtype
	 */
	public String getAttrbtype() {
		return attrbtype;
	}

	/**
	 * @param attrbtype the attrbtype to set
	 */
	public void setAttrbtype(String attrbtype) {
		this.attrbtype = attrbtype;
	}

	/**
	 * @return the attrbphysicaltype
	 */
	public String getAttrbphysicaltype() {
		return attrbphysicaltype;
	}

	/**
	 * @param attrbphysicaltype the attrbphysicaltype to set
	 */
	public void setAttrbphysicaltype(String attrbphysicaltype) {
		this.attrbphysicaltype = attrbphysicaltype;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the prgrmattrbs
	 */
	public Set<ProgramAttribute> getPrgrmattrbs() {
		return prgrmattrbs;
	}

	/**
	 * @param prgrmattrbs the prgrmattrbs to set
	 */
	public void setPrgrmattrbs(Set<ProgramAttribute> prgrmattrbs) {
		this.prgrmattrbs = prgrmattrbs;
	}

	/**
	 * @return the lnattrbs
	 */
	public Set<LoanAttribute> getLnattrbs() {
		return lnattrbs;
	}

	/**
	 * @param lnattrbs the lnattrbs to set
	 */
	public void setLnattrbs(Set<LoanAttribute> lnattrbs) {
		this.lnattrbs = lnattrbs;
	}

}

