package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
* Borrower generated by hbm2java
*/
public class Borrower implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8770996005163388519L;
	private long baid;
	private User user;
	private long brwrid;
	private String fname;
	private String lname;
	private String mname;
	private String add1;
	private String add2;
	private String city;
	private String state;
	private String zip;
	private String email;
	private String hphone;
	private String mphone;
	private String ophone;
	private Date dtlstupdt;
	private Long lstupdtuid;
	private String ssn;
	private String nid;
	private Character recordCode;
	
	private int brwrnos;
	private LoanProduct loanProduct;
	private String country;
	private Set<LoanBorrower> lnbrwrs = new HashSet<LoanBorrower>(0);

	public Borrower() {
	}

	public Borrower(long brwrid, String fname, String lname, String add1,
			String city, String state, String zip, String email, Date dtlstupdt) {
		this.brwrid = brwrid;
		this.fname = fname;
		this.lname = lname;
		this.add1 = add1;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.email = email;
		this.dtlstupdt = dtlstupdt;
	}

	public Borrower(User user, long brwrid, String fname, String lname,
			String mname, String add1, String add2, String city, String state,
			String zip, String email, String hphone, String mphone,
			String ophone, Date dtlstupdt, Long lstupdtuid, String ssn,
			String nid, Character recordCode, Set<LoanBorrower> lnbrwrs) {
		this.user = user;
		this.brwrid = brwrid;
		this.fname = fname;
		this.lname = lname;
		this.mname = mname;
		this.add1 = add1;
		this.add2 = add2;
		this.city = city;
		this.state = state;
		this.zip = zip;
		this.email = email;
		this.hphone = hphone;
		this.mphone = mphone;
		this.ophone = ophone;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
		this.ssn = ssn;
		this.nid = nid;
		this.recordCode = recordCode;
		this.lnbrwrs = lnbrwrs;
	}


	/**
	 * @return the baid
	 */
	public long getBaid() {
		return baid;
	}

	/**
	 * @param baid the baid to set
	 */
	public void setBaid(long baid) {
		this.baid = baid;
	}

	/**
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * @param user the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * @return the brwrid
	 */
	public long getBrwrid() {
		return brwrid;
	}

	/**
	 * @param brwrid the brwrid to set
	 */
	public void setBrwrid(long brwrid) {
		this.brwrid = brwrid;
	}

	/**
	 * @return the fname
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * @param fname the fname to set
	 */
	public void setFname(String fname) {
		this.fname = fname;
	}

	/**
	 * @return the lname
	 */
	public String getLname() {
		return lname;
	}

	/**
	 * @param lname the lname to set
	 */
	public void setLname(String lname) {
		this.lname = lname;
	}

	/**
	 * @return the mname
	 */
	public String getMname() {
		return mname;
	}

	/**
	 * @param mname the mname to set
	 */
	public void setMname(String mname) {
		this.mname = mname;
	}

	/**
	 * @return the add1
	 */
	public String getAdd1() {
		return add1;
	}

	/**
	 * @param add1 the add1 to set
	 */
	public void setAdd1(String add1) {
		this.add1 = add1;
	}

	/**
	 * @return the add2
	 */
	public String getAdd2() {
		return add2;
	}

	/**
	 * @param add2 the add2 to set
	 */
	public void setAdd2(String add2) {
		this.add2 = add2;
	}

	/**
	 * @return the city
	 */
	public String getCity() {
		return city;
	}

	/**
	 * @param city the city to set
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * @return the state
	 */
	public String getState() {
		return state;
	}

	/**
	 * @param state the state to set
	 */
	public void setState(String state) {
		this.state = state;
	}

	/**
	 * @return the zip
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * @param zip the zip to set
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * @return the email
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * @param email the email to set
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * @return the hphone
	 */
	public String getHphone() {
		return hphone;
	}

	/**
	 * @param hphone the hphone to set
	 */
	public void setHphone(String hphone) {
		this.hphone = hphone;
	}

	/**
	 * @return the mphone
	 */
	public String getMphone() {
		return mphone;
	}

	/**
	 * @param mphone the mphone to set
	 */
	public void setMphone(String mphone) {
		this.mphone = mphone;
	}

	/**
	 * @return the ophone
	 */
	public String getOphone() {
		return ophone;
	}

	/**
	 * @param ophone the ophone to set
	 */
	public void setOphone(String ophone) {
		this.ophone = ophone;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the ssn
	 */
	public String getSsn() {
		return ssn;
	}

	/**
	 * @param ssn the ssn to set
	 */
	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	/**
	 * @return the nid
	 */
	public String getNid() {
		return nid;
	}

	/**
	 * @param nid the nid to set
	 */
	public void setNid(String nid) {
		this.nid = nid;
	}

	/**
	 * @return the recordCode
	 */
	public Character getRecordCode() {
		return recordCode;
	}

	/**
	 * @param recordCode the recordCode to set
	 */
	public void setRecordCode(Character recordCode) {
		this.recordCode = recordCode;
	}

	/**
	 * @return the lnbrwrs
	 */
	public Set<LoanBorrower> getLnbrwrs() {
		return lnbrwrs;
	}

	/**
	 * @param lnbrwrs the lnbrwrs to set
	 */
	public void setLnbrwrs(Set<LoanBorrower> lnbrwrs) {
		this.lnbrwrs = lnbrwrs;
	}

	/**
	 * @return the brwrnos
	 */
	public int getBrwrnos() {
		return brwrnos;
	}

	/**
	 * @param brwrnos the brwrnos to set
	 */
	public void setBrwrnos(int brwrnos) {
		this.brwrnos = brwrnos;
	}

	/**
	 * @return the loanProduct
	 */
	public LoanProduct getLoanProduct() {
		return loanProduct;
	}

	/**
	 * @param loanProduct the loanProduct to set
	 */
	public void setLoanProduct(LoanProduct loanProduct) {
		this.loanProduct = loanProduct;
	}
	
	/**
	 * @return the country
	 */
	public String getCountry() {
		return country;
	}

	/**
	 * @param country the country to set
	 */
	public void setCountry(String country) {
		this.country = country;
	}

	public void addBorrower(User user,LoanProduct lnprdt,String ssn,String nid,int brwrnos){
		Date currentDate = new Date();

		this.setUser(user);
		this.setFname(user.getFname());
		this.setLname(user.getLname());
		this.setMname(user.getMname());
		this.setAdd1(user.getAdd1());
		this.setAdd2(user.getAdd2());
		this.setCity(user.getCity());
		this.setState(user.getState());
		this.setCountry(user.getCountry());
		this.setZip(user.getZip());
		this.setHphone(user.getHphone());
		this.setMphone(user.getMphone());
		this.setOphone(user.getOphone());
		this.setEmail(user.getEmail());
		this.setDtlstupdt(currentDate);
		this.setLstupdtuid(user.getLstupdtuid());
		this.setSsn(ssn);
		this.setNid(nid);
		this.setRecordCode('Y');
		this.setLoanProduct(lnprdt);
		this.setBrwrnos(brwrnos);
	}


}
