package com.mfic.data;
// default package
// Generated Sep 24, 2010 7:47:16 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;

import com.mfic.util.XmlHelper;


/**
 * Lncredit generated by hbm2java
 */
public class Lncredit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1565275063660670473L;
	
	private int idlnCredit;
	private long lid;
	private byte[] creport;
	private Date dtlstupdate;
	private String rpString;
	private long brwrid;

	public Lncredit() {
	}

	public Lncredit(Date dtlstupdate) {
		this.dtlstupdate = dtlstupdate;
	}

	public Lncredit(long lid, byte[] creport, Date dtlstupdate, long brwrid) {
		this.lid = lid;
		this.creport = creport;
		this.dtlstupdate = dtlstupdate;
		this.rpString = XmlHelper.format(new String(creport));
		this.brwrid = brwrid;
	}

	public Integer getIdlnCredit() {
		return this.idlnCredit;
	}

	public void setIdlnCredit(int idlnCredit) {
		this.idlnCredit = idlnCredit;
	}

	public long getLid() {
		return this.lid;
	}

	public void setLid(long lid) {
		this.lid = lid;
	}

	public byte[] getCreport() {
		return this.creport;
	}

	public void setCreport(byte[] creport) {
		this.creport = creport;
	}

	public Date getDtlstupdate() {
		return this.dtlstupdate;
	}

	public void setDtlstupdate(Date dtlstupdate) {
		this.dtlstupdate = dtlstupdate;
	}

	public void setRpString(String rpString) {
		this.rpString = rpString;
	}

	public String getRpString() {
		return rpString;
	}

	public void setBrwrid(long brwrid) {
		this.brwrid = brwrid;
	}

	public long getBrwrid() {
		return brwrid;
	}

}
