package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import com.mfic.util.AttributeType;

/**
* LoanAttribute generated by hbm2java
*/
public class LoanAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1576031353322240977L;
	private Long lnattrbid;
	private LoanApplication lnapp;
	private Attribute attrb;
	private String value;
	private Date dtlstupdt;
	private Long lstupdtuid;
	private String doclink;
	private Character recordCode;

	public LoanAttribute() {
	}

	public LoanAttribute(LoanApplication lnapp, Attribute attrb, Date dtlstupdt) {
		this.lnapp = lnapp;
		this.attrb = attrb;
		this.dtlstupdt = dtlstupdt;
	}

	public LoanAttribute(LoanApplication lnapp, Attribute attrb, String value, Date dtlstupdt,
			Long lstupdtuid, String doclink, Character recordCode) {
		this.lnapp = lnapp;
		this.attrb = attrb;
		this.value = value;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
		this.doclink = doclink;
		this.recordCode = recordCode;
	}



	/**
	 * @return the lnattrbid
	 */
	public Long getLnattrbid() {
		return lnattrbid;
	}

	/**
	 * @param lnattrbid the lnattrbid to set
	 */
	public void setLnattrbid(Long lnattrbid) {
		this.lnattrbid = lnattrbid;
	}

	/**
	 * @return the lnapp
	 */
	public LoanApplication getLnapp() {
		return lnapp;
	}

	/**
	 * @param lnapp the lnapp to set
	 */
	public void setLnapp(LoanApplication lnapp) {
		this.lnapp = lnapp;
	}

	/**
	 * @return the attrb
	 */
	public Attribute getAttrb() {
		return attrb;
	}

	/**
	 * @param attrb the attrb to set
	 */
	public void setAttrb(Attribute attrb) {
		this.attrb = attrb;
	}

	/**
	 * @return the value
	 */
	public String getValue() {
		return value;
	}

	/**
	 * @param value the value to set
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the doclink
	 */
	public String getDoclink() {
		return doclink;
	}

	/**
	 * @param doclink the doclink to set
	 */
	public void setDoclink(String doclink) {
		this.doclink = doclink;
	}

	/**
	 * @return the recordCode
	 */
	public Character getRecordCode() {
		return recordCode;
	}

	/**
	 * @param recordCode the recordCode to set
	 */
	public void setRecordCode(Character recordCode) {
		this.recordCode = recordCode;
	}

	public void addLoanAttribute(Attribute attribute, LoanApplication application, String doc,String val){
		Date currentDate = new Date();
		this.setAttrb(attribute);
		this.setLnapp(application);
		this.setDtlstupdt(currentDate);
		this.setLstupdtuid(getLstupdtuid());
		this.setRecordCode('Y');
		if(attribute.getAttrbtype().equalsIgnoreCase(AttributeType.DOC)){
			this.setDoclink(doc);
			this.setValue(null);
		} else {
			this.setDoclink(null);
			this.setValue(val);
		}
	}
	

}
