package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

/**
* LoanBorrowerId generated by hbm2java
*/

public class LoanBorrowerId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8989879961270568192L;
	private long lid;
	private long brwrid;

	public LoanBorrowerId() {
	}

	public LoanBorrowerId(long lid, long brwrid) {
		this.lid = lid;
		this.brwrid = brwrid;
	}


	/**
	 * @return the lid
	 */
	public long getLid() {
		return lid;
	}

	/**
	 * @param lid the lid to set
	 */
	public void setLid(long lid) {
		this.lid = lid;
	}

	/**
	 * @return the brwrid
	 */
	public long getBrwrid() {
		return brwrid;
	}

	/**
	 * @param brwrid the brwrid to set
	 */
	public void setBrwrid(long brwrid) {
		this.brwrid = brwrid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LoanBorrowerId))
			return false;
		LoanBorrowerId castOther = (LoanBorrowerId) other;

		return (this.getLid() == castOther.getLid())
				&& (this.getBrwrid() == castOther.getBrwrid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLid();
		result = 37 * result + (int) this.getBrwrid();
		return result;
	}

}
