package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
* LoanBorrower generated by hbm2java
*/
public class LoanBorrower implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6819289934981834576L;
	private LoanBorrowerId id;
	private LoanApplication lnapp;
	private Borrower brwr;
	private Date dtlstupdt;
	private Long lstupdtuid;

	public LoanBorrower() {
	}

	public LoanBorrower(LoanBorrowerId id, LoanApplication lnapp, Borrower brwr) {
		this.id = id;
		this.lnapp = lnapp;
		this.brwr = brwr;
	}

	public LoanBorrower(LoanBorrowerId id, LoanApplication lnapp, Borrower brwr, Date dtlstupdt,
			Long lstupdtuid) {
		this.id = id;
		this.lnapp = lnapp;
		this.brwr = brwr;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the id
	 */
	public LoanBorrowerId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(LoanBorrowerId id) {
		this.id = id;
	}

	/**
	 * @return the lnapp
	 */
	public LoanApplication getLnapp() {
		return lnapp;
	}

	/**
	 * @param lnapp the lnapp to set
	 */
	public void setLnapp(LoanApplication lnapp) {
		this.lnapp = lnapp;
	}

	/**
	 * @return the brwr
	 */
	public Borrower getBrwr() {
		return brwr;
	}

	/**
	 * @param brwr the brwr to set
	 */
	public void setBrwr(Borrower brwr) {
		this.brwr = brwr;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}
	

}

