package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
* LoanStatus generated by hbm2java
*/
public class LoanStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1139138602383828522L;
	private long lstid;
	private LoanApplication lnapp;
	private Date dtlstupdt;
	private Long lstupdtuid;
	private Integer step;
	private Long assigneduid;
	private Date dtassigned;
	private Date dtcompleted;
	private Character recordCode;

	
	public String toString(){
		return "lstid="+lstid+"step="+step+"assigneduid="+assigneduid+"dtassigned="+dtassigned+"dtcompleted="+dtcompleted+"recordCode"+recordCode;
	}
	public LoanStatus() {
	}

	public LoanStatus(LoanApplication lnapp, Date dtlstupdt) {
		this.lnapp = lnapp;
		this.dtlstupdt = dtlstupdt;
	}

	public LoanStatus(LoanApplication lnapp, Date dtlstupdt, Long lstupdtuid, Integer step,
			Long assigneduid, Date dtassigned, Date dtcompleted,
			Character recordCode) {
		this.lnapp = lnapp;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
		this.step = step;
		this.assigneduid = assigneduid;
		this.dtassigned = dtassigned;
		this.dtcompleted = dtcompleted;
		this.recordCode = recordCode;
	}



	/**
	 * @return the lstid
	 */
	public long getLstid() {
		return lstid;
	}

	/**
	 * @param lstid the lstid to set
	 */
	public void setLstid(long lstid) {
		this.lstid = lstid;
	}

	/**
	 * @return the lnapp
	 */
	public LoanApplication getLnapp() {
		return lnapp;
	}

	/**
	 * @param lnapp the lnapp to set
	 */
	public void setLnapp(LoanApplication lnapp) {
		this.lnapp = lnapp;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the step
	 */
	public Integer getStep() {
		return step;
	}

	/**
	 * @param step the step to set
	 */
	public void setStep(Integer step) {
		this.step = step;
	}

	/**
	 * @return the assigneduid
	 */
	public Long getAssigneduid() {
		return assigneduid;
	}

	/**
	 * @param assigneduid the assigneduid to set
	 */
	public void setAssigneduid(Long assigneduid) {
		this.assigneduid = assigneduid;
	}

	/**
	 * @return the dtassigned
	 */
	public Date getDtassigned() {
		return dtassigned;
	}

	/**
	 * @param dtassigned the dtassigned to set
	 */
	public void setDtassigned(Date dtassigned) {
		this.dtassigned = dtassigned;
	}

	/**
	 * @return the dtcompleted
	 */
	public Date getDtcompleted() {
		return dtcompleted;
	}

	/**
	 * @param dtcompleted the dtcompleted to set
	 */
	public void setDtcompleted(Date dtcompleted) {
		this.dtcompleted = dtcompleted;
	}

	/**
	 * @return the recordCode
	 */
	public Character getRecordCode() {
		return recordCode;
	}

	/**
	 * @param recordCode the recordCode to set
	 */
	public void setRecordCode(Character recordCode) {
		this.recordCode = recordCode;
	}

	/**  
	  * Set the new loan status by loan application id. 
	 */
	public void addLoanStatus(LoanApplication loanApplication){
		this.setLnapp(loanApplication);
		this.setDtlstupdt(loanApplication.getDtlstupdt());
		this.setLstupdtuid(loanApplication.getLstupdtuid());
		this.setStep(loanApplication.getStep());
		this.setAssigneduid((long) 1);
		this.setDtassigned(loanApplication.getDtlstupdt());
		this.setRecordCode(loanApplication.getRecordCode());
	}


}

