package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

/**
* ProgramAttributeId generated by hbm2java
*/
public class ProgramAttributeId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3179834199287528231L;
	private long lnprgid;
	private int attrbid;

	public ProgramAttributeId() {
	}

	public ProgramAttributeId(long lnprgid, int attrbid) {
		this.lnprgid = lnprgid;
		this.attrbid = attrbid;
	}


	/**
	 * @return the lnprgid
	 */
	public long getLnprgid() {
		return lnprgid;
	}

	/**
	 * @param lnprgid the lnprgid to set
	 */
	public void setLnprgid(long lnprgid) {
		this.lnprgid = lnprgid;
	}

	/**
	 * @return the attrbid
	 */
	public int getAttrbid() {
		return attrbid;
	}

	/**
	 * @param attrbid the attrbid to set
	 */
	public void setAttrbid(int attrbid) {
		this.attrbid = attrbid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProgramAttributeId))
			return false;
		ProgramAttributeId castOther = (ProgramAttributeId) other;

		return (this.getLnprgid() == castOther.getLnprgid())
				&& (this.getAttrbid() == castOther.getAttrbid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getLnprgid();
		result = 37 * result + this.getAttrbid();
		return result;
	}

}

