package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;


/**
* ProgramAttribute generated by hbm2java
*/
public class ProgramAttribute implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2861190023149435705L;
	private ProgramAttributeId id;
	private LoanProduct lnprdt;
	private Attribute attrb;
	private char scope;
	private Date dtlstupdt;
	private Long lstupdtuid;


	public ProgramAttribute() {
	}

	public ProgramAttribute(ProgramAttributeId id, LoanProduct lnprdt, Attribute attrb, char scope) {
		this.id = id;
		this.lnprdt = lnprdt;
		this.attrb = attrb;
		this.scope = scope;
	}

	public ProgramAttribute(ProgramAttributeId id, LoanProduct lnprdt, Attribute attrb, char scope,
			Date dtlstupdt, Long lstupdtuid) {
		this.id = id;
		this.lnprdt = lnprdt;
		this.attrb = attrb;
		this.scope = scope;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the id
	 */
	public ProgramAttributeId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(ProgramAttributeId id) {
		this.id = id;
	}

	/**
	 * @return the lnprdt
	 */
	public LoanProduct getLnprdt() {
		return lnprdt;
	}

	/**
	 * @param lnprdt the lnprdt to set
	 */
	public void setLnprdt(LoanProduct lnprdt) {
		this.lnprdt = lnprdt;
	}

	/**
	 * @return the attrb
	 */
	public Attribute getAttrb() {
		return attrb;
	}

	/**
	 * @param attrb the attrb to set
	 */
	public void setAttrb(Attribute attrb) {
		this.attrb = attrb;
	}

	/**
	 * @return the scope
	 */
	public char getScope() {
		return scope;
	}

	/**
	 * @param scope the scope to set
	 */
	public void setScope(char scope) {
		this.scope = scope;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	


}
