package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
* Role generated by hbm2java
*/
public class Role implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1439340117878030824L;
	private int rid;
	private String rolename;
	private String description;
	private Date dtlstupdt;
	private Long lstupdtuid;
	private Set<UserRole> uroles = new HashSet<UserRole>(0);

	public Role() {
	}

	public Role(int rid, String rolename, String description) {
		this.rid = rid;
		this.rolename = rolename;
		this.description = description;
	}

	public Role(int rid, String rolename, String description, Date dtlstupdt,
			Long lstupdtuid, Set<UserRole> uroles) {
		this.rid = rid;
		this.rolename = rolename;
		this.description = description;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
		this.uroles = uroles;
	}

	/**
	 * @return the rid
	 */
	public int getRid() {
		return rid;
	}

	/**
	 * @param rid the rid to set
	 */
	public void setRid(int rid) {
		this.rid = rid;
	}

	/**
	 * @return the rolename
	 */
	public String getRolename() {
		return rolename;
	}

	/**
	 * @param rolename the rolename to set
	 */
	public void setRolename(String rolename) {
		this.rolename = rolename;
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the uroles
	 */
	public Set<UserRole> getUroles() {
		return uroles;
	}

	/**
	 * @param uroles the uroles to set
	 */
	public void setUroles(Set<UserRole> uroles) {
		this.uroles = uroles;
	}



}
