package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA


/**
* UserRoleId generated by hbm2java
*/
public class UserRoleId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7385923609944608124L;
	private long uid;
	private int rid;
	private long lnprdtid;

	public UserRoleId() {
	}

	public UserRoleId(long uid, int rid, long lnprdtid) {
		this.uid = uid;
		this.rid = rid;
		this.lnprdtid = lnprdtid;
	}

	/**
	 * @return the uid
	 */
	public long getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(long uid) {
		this.uid = uid;
	}

	/**
	 * @return the rid
	 */
	public int getRid() {
		return rid;
	}

	/**
	 * @param rid the rid to set
	 */
	public void setRid(int rid) {
		this.rid = rid;
	}

	/**
	 * @return the lnprdtid
	 */
	public long getLnprdtid() {
		return lnprdtid;
	}

	/**
	 * @param lnprdtid the lnprdtid to set
	 */
	public void setLnprdtid(long lnprdtid) {
		this.lnprdtid = lnprdtid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserRoleId))
			return false;
		UserRoleId castOther = (UserRoleId) other;

		return (this.getUid() == castOther.getUid())
				&& (this.getRid() == castOther.getRid())
				&& (this.getLnprdtid() == castOther.getLnprdtid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUid();
		result = 37 * result + this.getRid();
		result = 37 * result + (int) this.getLnprdtid();
		return result;
	}

}
