package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
* UserPassword generated by hbm2java
*/
public class UserPassword implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3484548830094410836L;
	private UserPasswordId id;
	private User user;
	private String pwd;
	private Date dteff;

	private Date dtlstupdt;
	private Long lstupdtuid;

	private String confirmPwd;
	
	public UserPassword() {
	}

	public UserPassword(UserPasswordId id, User user, String pwd, Date dteff) {
		this.id = id;
		this.user = user;
		this.pwd = pwd;
		this.dteff = dteff;
	}

	public UserPassword(UserPasswordId id, User user, String pwd, Date dteff, Date dtlstupdt,
			Long lstupdtuid) {
		this.id = id;
		this.user = user;
		this.pwd = pwd;
		this.dteff = dteff;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
	}


	/**
	 * @return the id
	 */
	public UserPasswordId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(UserPasswordId id) {
		this.id = id;
	}

	/**
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * @param user the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * @return the pwd
	 */
	public String getPwd() {
		return pwd;
	}

	/**
	 * @param pwd the pwd to set
	 */
	public void setPwd(String pwd) {
		this.pwd = pwd;
	}

	/**
	 * @return the dteff
	 */
	public Date getDteff() {
		return dteff;
	}

	/**
	 * @param dteff the dteff to set
	 */
	public void setDteff(Date dteff) {
		this.dteff = dteff;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the confirmPwd
	 */
	public String getConfirmPwd() {
		return confirmPwd;
	}

	/**
	 * @param confirmPwd the confirmPwd to set
	 */
	public void setConfirmPwd(String confirmPwd) {
		this.confirmPwd = confirmPwd;
	}
}
