package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;


/**
* UserRole generated by hbm2java
*/
public class UserRole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7304218079190215942L;
	private UserRoleId id;
	private LoanProduct lnprdt;
	private User user;
	private Role role;
	private Date dtlstupdt;
	private Long lstupdtuid;

	public UserRole() {
	}

	public UserRole(UserRoleId id, LoanProduct lnprdt, User user, Role role) {
		this.id = id;
		this.lnprdt = lnprdt;
		this.user = user;
		this.role = role;
	}

	public UserRole(UserRoleId id, LoanProduct lnprdt, User user, Role role,
			Date dtlstupdt, Long lstupdtuid) {
		this.id = id;
		this.lnprdt = lnprdt;
		this.user = user;
		this.role = role;
		this.dtlstupdt = dtlstupdt;
		this.lstupdtuid = lstupdtuid;
	}

	/**
	 * @return the id
	 */
	public UserRoleId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(UserRoleId id) {
		this.id = id;
	}

	/**
	 * @return the lnprdt
	 */
	public LoanProduct getLnprdt() {
		return lnprdt;
	}

	/**
	 * @param lnprdt the lnprdt to set
	 */
	public void setLnprdt(LoanProduct lnprdt) {
		this.lnprdt = lnprdt;
	}

	/**
	 * @return the user
	 */
	public User getUser() {
		return user;
	}

	/**
	 * @param user the user to set
	 */
	public void setUser(User user) {
		this.user = user;
	}

	/**
	 * @return the role
	 */
	public Role getRole() {
		return role;
	}

	/**
	 * @param role the role to set
	 */
	public void setRole(Role role) {
		this.role = role;
	}

	/**
	 * @return the dtlstupdt
	 */
	public Date getDtlstupdt() {
		return dtlstupdt;
	}

	/**
	 * @param dtlstupdt the dtlstupdt to set
	 */
	public void setDtlstupdt(Date dtlstupdt) {
		this.dtlstupdt = dtlstupdt;
	}

	/**
	 * @return the lstupdtuid
	 */
	public Long getLstupdtuid() {
		return lstupdtuid;
	}

	/**
	 * @param lstupdtuid the lstupdtuid to set
	 */
	public void setLstupdtuid(Long lstupdtuid) {
		this.lstupdtuid = lstupdtuid;
	}


}
