package com.mfic.data;

//Generated Jun 17, 2010 11:00:29 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;

/**
* UserPasswordId generated by hbm2java
*/
public class UserPasswordId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -839826071906074588L;
	private long uid;
	private Date dtexp;

	public UserPasswordId() {
	}

	public UserPasswordId(long uid, Date dtexp) {
		this.uid = uid;
		this.dtexp = dtexp;
	}

	/**
	 * @return the uid
	 */
	public long getUid() {
		return uid;
	}

	/**
	 * @param uid the uid to set
	 */
	public void setUid(long uid) {
		this.uid = uid;
	}

	/**
	 * @return the dtexp
	 */
	public Date getDtexp() {
		return dtexp;
	}

	/**
	 * @param dtexp the dtexp to set
	 */
	public void setDtexp(Date dtexp) {
		this.dtexp = dtexp;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UserPasswordId))
			return false;
		UserPasswordId castOther = (UserPasswordId) other;

		return (this.getUid() == castOther.getUid())
				&& ((this.getDtexp() == castOther.getDtexp()) || (this
						.getDtexp() != null
						&& castOther.getDtexp() != null && this.getDtexp()
						.equals(castOther.getDtexp())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUid();
		result = 37 * result
				+ (getDtexp() == null ? 0 : this.getDtexp().hashCode());
		return result;
	}

}
